# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on GitHub Actions and Azure App Service: https://learn.microsoft.com/azure/app-service/deploy-azure-actions

name: Build and deploy Node.js app to Azure Web App - UWShubhiAssignment8

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15290A506A1E469BB596298947EBC631 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_38A650733F574A0ABE894BDF868E3A86 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7415AF937855423EB14EA18F10E9C599 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'UWShubhiAssignment8'
          slot-name: 'Production'
          package: '.'
